
-- Create Tablespaces for EXPENSE
CREATE BIGFILE TABLESPACE EXPENSE01 DATAFILE 'EXPENSE01.dat' SIZE 20M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE TMP_EXPENSE01 TEMPFILE 'TMP_EXPENSE01.dbf' SIZE 10M AUTOEXTEND ON;
CREATE BIGFILE TABLESPACE EXPENSE_INDX01 DATAFILE 'EXPENSE_INDX01.dat' SIZE 20M AUTOEXTEND ON;


-- Create Users[/schema] for EXPENSE
CREATE USER EXPENSE IDENTIFIED BY EXPENSE DEFAULT TABLESPACE EXPENSE01 TEMPORARY TABLESPACE TMP_EXPENSE01 QUOTA 20M on EXPENSE01;


-- Grants
grant all privileges to EXPENSE;
